name: Publish @m3ter-com/react-pivottable to NPM
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        # Prevent malicous scripts stealing our NPM token
        run: npm install --ignore-scripts
      - name: Run tests
        run: npm run test
      - name: Publish package
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
        run: npm run build
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}